name: Test native assets

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  test:
    strategy:
      matrix:
        os: [ubuntu-24.04, ubuntu-24.04-arm, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v6
      - uses: dart-lang/setup-dart@v1
        with:
          sdk: '3.13.0'
      - uses: dtolnay/rust-toolchain@1.90.0
      - run: dart pub get --no-example
      - run: dart analyze lib test hook
      - run: dart test
      - name: Rust tests
        if: matrix.os == 'ubuntu-24.04'
        working-directory: src/serai/hrf
        run: cargo test --locked --workspace --exclude bitcoin-serai
